# in your terminal, run conda: conda env create -f timex-environment.yaml
name: timex
channels:
  - conda-forge
  - cmutel
  - diepers
dependencies:
  - brightway25 # for Linux/Windows/macOS(x64)
  # - brightway25_nosolver # switch to this if you're on a macOS ARM machine
  # - scikit-umfpack # also required for macOS ARM
  - bw_temporalis
  - matplotlib
  - seaborn
  - dynamic_characterization
