# in your terminal, run conda: conda env create -f tictac-environment.yaml

name: tictac
channels:
  - romainsacchi
  - defaults
  - conda-forge
  - cmutel
dependencies:
  - python=3.10
  - premise
  - jupyterlab
  - matplotlib
  - unfold  
  - bw_temporalis
  - seaborn