# in your terminal, run conda: conda env create -f timex-environment.yaml
name: timex
channels:
  - conda-forge
  - cmutel
dependencies:
  - brightway25 # for Linux/Windows/macOS(x64)
  # - brightway25_nosolver # for required for macOS ARM
  # - scikit-umfpack # for required for macOS ARM
  - bw_temporalis
  - matplotlib
  - seaborn